### ISSUE TITLE
Bad Cast?

### ISSUE THREAD

**Issue by bocciab** [backtrace-labs/backtrace-csharp#11]
https://github.com/backtrace-labs/backtrace-csharp/blob/6d28690cd9085b608ecb123faac9c470f298caf0/Backtrace/Services/BacktraceApi.cs#L82

This seems like a bad cast - Any other types derived from BacktraceReportBase will end up nulled out here. Is it intentional that only the BacktraceReport subclass be allowed? If so, the Report/ReportBase seems needlessly complex and confusing.

**Comment by arthur2** [comment]
@bocciab thanks for the good catch! will address this in the next patch.

**Comment by arthur2** [comment]
@bocciab I want to give you a quick update on this issue: we have addressed this casting issue in release 1.3.0. Thanks again for the feedback and please let us know if there're any other outstanding issues.
