### ISSUE TITLE
LoadReports throws NullReferenceException if invalid JSON found

### ISSUE THREAD

**Issue by tomalakgeretkal** [backtrace-labs/backtrace-csharp#25]
`LoadReports` (https://github.com/backtrace-labs/backtrace-csharp/blob/dev/Backtrace/BacktraceDatabase.cs#L373) doesn't handle the potential null returned by `ReadFromFile` when invalid JSON is found (https://github.com/backtrace-labs/backtrace-csharp/blob/dev/Backtrace/Model/Database/BacktraceDatabaseRecord.cs#L314) before using `record`.

Should we have a `if (!record) continue;` after the `ReadFromFile` call?

**Comment by konraddysput** [comment]
Hello!

Thanks for your suggestion! Today we publish new version of backtrace-csharp library with this change. 

https://www.nuget.org/packages/Backtrace/2.1.4

Thanks!
