### ISSUE TITLE
Adding a null attribute will result in no crash reports

### ISSUE THREAD

**Issue by adammarks** [backtrace-labs/backtrace-csharp#28]
Specifically,  if I add a null attribute, then try to save a report to the database, it fails.

Example Code:
```
string attrib;
_client.Attributes["attrib"] = attrib;
_client.Database?.Add( report, _client.Attributes, _client.MiniDumpType );
```

This can happen when assigning strings to attributes which could be null.

Workaround is to check before assigning a attribute
```
string attrib;
if ( !String.IsNullOrEmpty(attrib) )
{
_client.Attributes["attrib"] = attrib;
}
```

**Comment by konraddysput** [comment]
Thanks for this report. I will check serializer settings again and ship an update if something is wrong there. I will keep you posted with our next steps.

**Comment by konraddysput** [comment]
In version 2.1.7 I pushed a fix to solve this problem. I found that we're trying to analyse attribute type without checking if attribute is null or not. Thanks for that. Could you please confirm, latest change fix this issue?

**Comment by adammarks** [comment]
@konraddysput I confirmed that 2.1.7 fixes this issue also.

**Comment by konraddysput** [comment]
Thanks for confirmation. Version 2.1.7 fixes this issue. Closing ticket.
