### ISSUE TITLE
Crash if EXE is not a .NET EXE

### ISSUE THREAD

**Issue by adammarks** [backtrace-labs/backtrace-csharp#29]
Our EXE is a native EXE that ends up calling into .NET through interop.

In this situation we have found the following code that crashes with a index out of range exception and then we end up losing the crash report.

In BacktraceAttributes.cs
```
        private void SetDebuggerAttributes(Assembly callingAssembly)
        {
            object[] attribs = callingAssembly.GetCustomAttributes(typeof(DebuggableAttribute), false);
   ...
            if (attribs[0] is DebuggableAttribute debuggableAttribute)   <------ this will throw a index out of range exception
```
The exception is thrown because a native EXE won't have the custom attributes on it

I would recommend changing the code in the if statement to something like the following
```
            if ( attribs != null && attribs.Length > 0 &&
                 attribs[0] is DebuggableAttribute debuggableAttribute )
```

**Comment by konraddysput** [comment]
Thanks @adammarks for this information.


I've checked C# library source code and I found that we're checking attribute array earlier. I think we just missed there `return;` for first if. 

Let me bring code here to give you more color

```csharp
           object[] attribs = callingAssembly.GetCustomAttributes(typeof(DebuggableAttribute), false);
            // If the 'DebuggableAttribute' is not found then it is definitely an OPTIMIZED build
            if (attribs == null || !attribs.Any())
            {
                Attributes["build.debug"] = false;
                Attributes["build.jit"] = true;
                Attributes["build.type"] = "Release";
                return; // <- this is what we're missig 
            }
            // Just because the 'DebuggableAttribute' is found doesn't necessarily mean
            // it's a DEBUG build; we have to check the JIT Optimization flag
            // i.e. it could have the "generate PDB" checked but have JIT Optimization enabled
            if (attribs[0] is DebuggableAttribute debuggableAttribute)
            {
                Attributes["build.debug"] = true;
                Attributes["build.jit"] = !debuggableAttribute.IsJITOptimizerDisabled;
                Attributes["build.type"] = debuggableAttribute.IsJITOptimizerDisabled
                    ? "Debug" : "Release";
                // check for Debug Output "full" or "pdb-only"
                Attributes["build.output"] = (debuggableAttribute.DebuggingFlags &
                    DebuggableAttribute.DebuggingModes.Default) !=
                    DebuggableAttribute.DebuggingModes.None
                    ? "Full" : "pdb-only";
            }
```
This change will be available in next C# library update. Please expect release notes soon!

**Comment by adammarks** [comment]
:+1: Makes sense,   I considered that but the comment threw me off,  it made me think that there was additional checking that could be done.

**Comment by adammarks** [comment]
@konraddysput When do you plan to make this change and push a nuget package?   Asking because this issue is keeping us from shipping something and we could get a build going to make our own nuget package internally if it looks like it will be a while.

**Comment by konraddysput** [comment]
@adammarks 
I just pushed new version. Could you please download latest Backtrace version and tell me if it fixed your problem?

**Comment by adammarks** [comment]
@konraddysput 2.1.7 does appear to fix this problem.   Thanks for the quick turnaround on this!
