### ISSUE TITLE
Crashes appear to be lost while offline

### ISSUE THREAD

**Issue by adammarks** [backtrace-labs/backtrace-csharp#30]
We recently added the backtrace-csharp SDK to a product and noticed the following behavior while offline.

While offline if a crash occurs, it is taken correctly, it is added to the cache directory.

While still offline when restarting the application, the crash is deleted.

Is this behavior expected/by design?   We would have expected the crash to continue to be saved while offline.

**Comment by konraddysput** [comment]
Hey @adammarks,

Yes - on database startup, we're checking data in cache directory and try to send them. If we're able to send them, we're removing crash data from cache directory.

**Comment by adammarks** [comment]
@konraddysput This behavior should be fine for now.  We just wanted to make sure it was expected.
